spring:
  application:
    name: iotfeds-symbiote-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: optional:file:/home/application.yaml

logging:
  level:
    ROOT: DEBUG
configuration:
  keystorePath: testKeystore.jks
  keystorePassword: testKeystore
#  coreAAMAddress: https://iotfeds-symbiotecore.intracom-telecom.com
#  coreAAMAddress: https://intracom-core.symbiote-h2020.eu
  coreAAMAddress: https://safety4rail-symbiotecore.intracom-telecom.com

springfox:
  documentation:
    swagger-ui:
      base-url: /symbioteapi
    openApi:
      v3:
        path: /symbioteapi/v3/api-docs
    swagger:
      v2:
        path: /symbioteapi/v2/api-docs
